/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongkham;

import DAO.BenhNhanDAO;
import Entity.BacSi;
import Entity.Benhnhan;
import Entity.Benhnhan.BenhNhanModalCallback;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import util.Auth;
import util.MsgBox;
import util.Xjdbc;

/**
 *
 * @author ADMIN
 */
public class BenhNhanModal extends javax.swing.JDialog {

    private Boolean isUpdate; // Check xem đang cập nhật hay tạo mới
    private BenhNhanModalCallback callback; // Trường callback

    public BenhNhanModal(java.awt.Frame parent, boolean isVisible, Boolean isUpdate, BenhNhanModalCallback callback) {
        super(parent, isVisible);
        initComponents();
        this.isUpdate = isUpdate; // Lưu trạng thái
        this.callback = callback; // Gán callback
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        buttonGroupBaoHiem = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        rdoYes = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        btnNew = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnNew2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(738, 932));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Thông Tin Bệnh Nhân");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(15, 5, 180, 22);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(3, 32, 890, 3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ và tên");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 77, 22);

        txtMaBN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtMaBN);
        txtMaBN.setBounds(140, 40, 410, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã BN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 40, 100, 22);

        txtTenBN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtTenBN);
        txtTenBN.setBounds(140, 85, 410, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Giới tính");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 230, 66, 22);

        buttonGroupGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel2.add(rdoNam);
        rdoNam.setBounds(140, 230, 49, 21);

        buttonGroupGioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel2.add(rdoNu);
        rdoNu.setBounds(210, 230, 39, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Địa chỉ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 270, 54, 22);

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtDiaChi);
        txtDiaChi.setBounds(140, 270, 410, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bảo hiểm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 330, 90, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Năm sinh");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 140, 74, 22);

        txtTuoi.setEditable(false);
        txtTuoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtTuoi);
        txtTuoi.setBounds(280, 140, 44, 26);

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtNgaySinh);
        txtNgaySinh.setBounds(140, 140, 121, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 180, 110, 22);

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtSDT);
        txtSDT.setBounds(140, 180, 410, 26);

        buttonGroupBaoHiem.add(rdoYes);
        rdoYes.setText("Có");
        jPanel2.add(rdoYes);
        rdoYes.setBounds(140, 330, 38, 21);

        buttonGroupBaoHiem.add(rdoNo);
        rdoNo.setText("Không");
        jPanel2.add(rdoNo);
        rdoNo.setBounds(210, 330, 58, 21);

        btnNew.setText("Nhập Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew);
        btnNew.setBounds(660, 0, 100, 50);

        btnExit1.setText("Đóng");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit1);
        btnExit1.setBounds(320, 400, 110, 30);

        btnAdd1.setText("Xác nhận");
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd1);
        btnAdd1.setBounds(440, 400, 110, 30);

        btnNew2.setText("Làm mới");
        btnNew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew2);
        btnNew2.setBounds(450, 7, 100, 23);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 580, 480));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/vector-MAY-2020-112.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew2ActionPerformed
        // TODO add your handling code here:
        this.clearForm();
        // Check if txtMaBS is disabled, and enable it if necessary
        if (!txtMaBN.isEnabled()) {
            txtMaBN.setEnabled(true);
        }
    }//GEN-LAST:event_btnNew2ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền thực hiện các tác vụ này!");
            return;
        }
        if (checkform()) {
            if (this.isUpdate) {
                this.update();
            } else {
                this.insert();
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền thực hiện các tác vụ này!");
            return;
        }
        if (checkform()) {
            if (checkInsert()) {
                this.insert();
            }
        }
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        this.clearForm();
        if (!txtMaBN.isEnabled()) {
            txtMaBN.setEnabled(true);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenhNhanModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenhNhanModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenhNhanModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenhNhanModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BenhNhanModal dialog = new BenhNhanModal(new javax.swing.JFrame(), true, false, new BenhNhanModalCallback() {
                    @Override
                    public void onBenhNhanAdded() {

                    }
                });
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNew2;
    private javax.swing.ButtonGroup buttonGroupBaoHiem;
    private javax.swing.ButtonGroup buttonGroupGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoYes;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenBN;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables

    BenhNhanDAO dao = new BenhNhanDAO();
    int row = -1;

    void init() {
        setLocationRelativeTo(null); // đưa cửa sổ ra giữa màn hình

    }

    Benhnhan getForm() {
        Benhnhan bn = new Benhnhan();
        bn.setMaBN(txtMaBN.getText());
        bn.setTenBN(txtTenBN.getText());
        bn.setNgaySinh(txtNgaySinh.getText());
        if (rdoNam.isSelected()) {
            bn.setGioiTinh(rdoNam.getText());
        }
        if (rdoNu.isSelected()) {
            bn.setGioiTinh(rdoNu.getText());
        }
        bn.setDiachi(txtDiaChi.getText());
        bn.setBaoHiem(rdoYes.isSelected());
        bn.setSDT(txtSDT.getText());
        return bn;
    }

    void setForm(Benhnhan bn) {
        txtMaBN.setText(bn.getMaBN());
        txtTenBN.setText(bn.getTenBN());
        // Format the date from ngaysinh (String) to DD/MM/YYYY
        String ngaysinhStr = bn.getNgaySinh(); // Assuming this returns a date in "yyyy-MM-dd" format
        if (ngaysinhStr != null) {
            try {
                SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date date = inputFormat.parse(ngaysinhStr);
                String formattedDate = outputFormat.format(date);
                txtNgaySinh.setText(formattedDate);
            } catch (ParseException e) {
                e.printStackTrace();
                txtNgaySinh.setText(""); // Handle parsing error
            }
        } else {
            txtNgaySinh.setText(""); // Handle null case
        }

        if (bn.getGioiTinh().equalsIgnoreCase("Nam")) {
            rdoNam.setSelected(true);
        } else if (bn.getGioiTinh().equalsIgnoreCase("Nữ")) {
            rdoNu.setSelected(true);
        }
        txtDiaChi.setText(bn.getDiachi());
        rdoYes.setSelected(bn.isBaoHiem());
        rdoNo.setSelected(!bn.isBaoHiem());
        txtSDT.setText(String.valueOf(bn.getSDT()));
        txtTuoi.setText(String.valueOf(tuoi()));
    }

    void clearForm() {//btnMoi
        txtMaBN.setText("");
        txtTenBN.setText("");
        txtTuoi.setText("");
        rdoNam.setSelected(true);
        txtDiaChi.setText("");
        rdoYes.setSelected(true);
        txtSDT.setText("");
        txtNgaySinh.setText("");
        this.row = -1;
        // this.updateStatus();
    }

    void insert() {
        Benhnhan bn = this.getForm();
        try {
            // Convert the date format from dd/MM/yyyy to yyyy-MM-dd
            String inputDate = bn.getNgaySinh(); // Assuming ngaySinh is a String in dd/MM/yyyy format

            // Define the date format you expect to receive (dd/MM/yyyy)
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = inputFormat.parse(inputDate);  // Parse the input date

            // Define the date format the database expects (yyyy-MM-dd)
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = outputFormat.format(date);  // Format the date

            // Set the formatted date back into the object
            bn.setNgaySinh(formattedDate);
            dao.insert(bn);

            this.clearForm(); // xóa trắng form
            MsgBox.alert(this, "Thêm mới thành công!");
            if (callback != null) {
                callback.onBenhNhanAdded();// Gọi callback sau khi cập nhật thành công
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            System.out.println(e);
        }
    }

    void update() {
        Benhnhan bn = this.getForm();
        try {
            String inputDate = bn.getNgaySinh(); // Assuming ngaySinh is a String in dd/MM/yyyy format

            // Define the date format you expect to receive (dd/MM/yyyy)
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = inputFormat.parse(inputDate);  // Parse the input date

            // Define the date format the database expects (yyyy-MM-dd)
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = outputFormat.format(date);  // Format the date

            // Set the formatted date back into the object
            bn.setNgaySinh(formattedDate);
            dao.update(bn); // cập nhật

            this.setForm(bn);

            MsgBox.alert(this, "Cập nhật thành công!");
            if (callback != null) {
                callback.onBenhNhanAdded();// Gọi callback sau khi cập nhật thành công
            }

        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    boolean checkform() {
        String sdt = "0[0-9]{9,10}";
        String regex = "^\\d{2}/\\d{2}/\\d{4}$";
        if (txtMaBN.getText().length() == 0) {
            MsgBox.alert(this, "Không để trống mã bệnh nhân");
            return false;
        } else if (txtTenBN.getText().length() == 0) {
            MsgBox.alert(this, "Không để trống họ tên");
            return false;
        } else if (txtNgaySinh.getText().length() == 0) {
            MsgBox.alert(this, "Không để trống ngày sinh");
            return false;
        } else if (!txtNgaySinh.getText().matches(regex)) {
            MsgBox.alert(this, "Bạn nhập sai định dạng ngày sinh, hãy kiểm tra lại(DD/MM/YYYY)!");
            return false;
        } else if (txtDiaChi.getText().length() == 0) {
            MsgBox.alert(this, "Không để trống địa chỉ");
            return false;
        } else if (txtSDT.getText().length() == 0) {
            MsgBox.alert(this, "Không để trống SDT");
            return false;
        } else if (!txtSDT.getText().matches(sdt)) {
            MsgBox.alert(this, "Không đúng định dạng số điện thoại!!!");
            return false;
        }

        return true;
    }

    int tuoi() {
        int namNgaySinh = 0;
        Benhnhan list = dao.selectById(txtMaBN.getText());
        String ngaysinh = list.getNgaySinh();
        String[] parts = ngaysinh.split("-");
        String part1 = parts[0];
        namNgaySinh = Integer.parseInt(String.valueOf(part1));
        int namHienTai = Calendar.getInstance().get(Calendar.YEAR);
        int tuoi = namHienTai - namNgaySinh;
        return tuoi;
    }

    public List<String> selectID() {
        String sql = "select MaBN from BenhNhan";
        List<String> list = new ArrayList<>();
        try {
            ResultSet rs = Xjdbc.query(sql);
            while (rs.next()) {
                list.add(rs.getString("MaBN"));
            }
            rs.getStatement().getConnection().close();
            return list;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    boolean checkInsert() {
        List<String> list = selectID();
        for (String ma : list) {
            if (txtMaBN.getText().equalsIgnoreCase(ma)) {
                MsgBox.alert(this, "Mã bệnh nhân đã tồn tại!");
                return false;
            }
        }
        return true;
    }

}
