/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongkham;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import util.Auth;
import util.MsgBox;
import util.setColorSystem;

/**
 *
 * @author ADMIN
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        init();
//        panel.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPhieuKham = new javax.swing.JLabel();
        lblBenhNhan = new javax.swing.JLabel();
        lblThuoc = new javax.swing.JLabel();
        lblBacSi = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblClock1 = new javax.swing.JLabel();
        lblTextBacSi = new javax.swing.JLabel();
        lblBenhNhanText = new javax.swing.JLabel();
        lblThuocText = new javax.swing.JLabel();
        lblPhieuKhamText = new javax.swing.JLabel();
        lblDonThoc = new javax.swing.JLabel();
        lblDonThuocText = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        lblDoanhThuText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniLogout = new javax.swing.JMenuItem();
        mniEXIT = new javax.swing.JMenuItem();
        mniBS = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mniBN = new javax.swing.JMenuItem();
        mniThuoc = new javax.swing.JMenuItem();
        mniDT = new javax.swing.JMenuItem();
        mniPK = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mniHuongDan = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\DuAn1\\QuanLyPhongKham\\src\\Background\\effect.gif")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        lblPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/phieukham1.png"))); // NOI18N
        lblPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPhieuKhamMouseExited(evt);
            }
        });
        jPanel1.add(lblPhieuKham);
        lblPhieuKham.setBounds(450, 490, 170, 170);

        lblBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Victim1.png"))); // NOI18N
        lblBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBenhNhanMouseExited(evt);
            }
        });
        jPanel1.add(lblBenhNhan);
        lblBenhNhan.setBounds(180, 500, 170, 170);

        lblThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/medical1.png"))); // NOI18N
        lblThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThuocMouseExited(evt);
            }
        });
        jPanel1.add(lblThuoc);
        lblThuoc.setBounds(50, 270, 170, 170);

        lblBacSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/doctor1.png"))); // NOI18N
        lblBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBacSiMouseExited(evt);
            }
        });
        jPanel1.add(lblBacSi);
        lblBacSi.setBounds(160, 20, 170, 170);

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clock.png"))); // NOI18N
        jPanel1.add(lblClock);
        lblClock.setBounds(1120, 840, 140, 50);

        lblClock1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        lblClock1.setText("Hệ Cơ Sở Quản Trị");
        jPanel1.add(lblClock1);
        lblClock1.setBounds(0, 840, 190, 50);

        lblTextBacSi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextBacSi.setForeground(java.awt.Color.blue);
        lblTextBacSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextBacSi.setText("Bác Sĩ");
        lblTextBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTextBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTextBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTextBacSiMouseExited(evt);
            }
        });
        jPanel1.add(lblTextBacSi);
        lblTextBacSi.setBounds(190, 190, 110, 30);

        lblBenhNhanText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBenhNhanText.setForeground(java.awt.Color.blue);
        lblBenhNhanText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBenhNhanText.setText("Bệnh Nhân");
        lblBenhNhanText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBenhNhanTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBenhNhanTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBenhNhanTextMouseExited(evt);
            }
        });
        jPanel1.add(lblBenhNhanText);
        lblBenhNhanText.setBounds(210, 680, 110, 30);

        lblThuocText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThuocText.setForeground(java.awt.Color.blue);
        lblThuocText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuocText.setText("Thuốc");
        lblThuocText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuocTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThuocTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThuocTextMouseExited(evt);
            }
        });
        jPanel1.add(lblThuocText);
        lblThuocText.setBounds(80, 450, 90, 30);

        lblPhieuKhamText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhieuKhamText.setForeground(java.awt.Color.blue);
        lblPhieuKhamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhieuKhamText.setText("Phiếu Khám");
        lblPhieuKhamText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhieuKhamTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhieuKhamTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPhieuKhamTextMouseExited(evt);
            }
        });
        jPanel1.add(lblPhieuKhamText);
        lblPhieuKhamText.setBounds(470, 670, 130, 30);

        lblDonThoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bill medical 1.png"))); // NOI18N
        lblDonThoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDonThocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDonThocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDonThocMouseExited(evt);
            }
        });
        jPanel1.add(lblDonThoc);
        lblDonThoc.setBounds(580, 270, 180, 160);

        lblDonThuocText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDonThuocText.setForeground(java.awt.Color.blue);
        lblDonThuocText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonThuocText.setText("Đơn Thuốc");
        lblDonThuocText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDonThuocTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDonThuocTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDonThuocTextMouseExited(evt);
            }
        });
        jPanel1.add(lblDonThuocText);
        lblDonThuocText.setBounds(620, 440, 120, 30);

        lblDoanhThu.setFont(new java.awt.Font("VNI-Vari", 0, 150)); // NOI18N
        lblDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThu.setText("$");
        lblDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseExited(evt);
            }
        });
        jPanel1.add(lblDoanhThu);
        lblDoanhThu.setBounds(450, 10, 170, 180);

        lblDoanhThuText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDoanhThuText.setForeground(java.awt.Color.blue);
        lblDoanhThuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuText.setText("Doanh Thu");
        lblDoanhThuText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseExited(evt);
            }
        });
        jPanel1.add(lblDoanhThuText);
        lblDoanhThuText.setBounds(480, 190, 110, 30);

        jLabel2.setFont(new java.awt.Font(".VnBahamasB", 0, 270)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("+");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 260, 230, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\DuAn1\\QuanLyPhongKham\\src\\Background\\effect.gif")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 530, 450);

        lblBackGround.setForeground(new java.awt.Color(204, 204, 255));
        lblBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Index.jpeg"))); // NOI18N
        jPanel1.add(lblBackGround);
        lblBackGround.setBounds(0, 0, 1260, 891);

        jMenu1.setText("Hệ Thống");

        mniLogout.setText("Đăng Xuất");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogout);

        mniEXIT.setText("Kết Thúc");
        mniEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEXITActionPerformed(evt);
            }
        });
        jMenu1.add(mniEXIT);

        jMenuBar1.add(jMenu1);

        mniBS.setText("Quản Lý");

        jMenuItem3.setText("Quản Lý Bác Sĩ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mniBS.add(jMenuItem3);

        mniBN.setText("Quản Lý Bệnh Nhân");
        mniBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBNActionPerformed(evt);
            }
        });
        mniBS.add(mniBN);

        mniThuoc.setText("Quản Lý Thuốc");
        mniThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniThuocMouseClicked(evt);
            }
        });
        mniThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThuocActionPerformed(evt);
            }
        });
        mniBS.add(mniThuoc);

        mniDT.setText("Quản Lý Đơn Thuốc");
        mniDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDTMouseClicked(evt);
            }
        });
        mniDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDTActionPerformed(evt);
            }
        });
        mniBS.add(mniDT);

        mniPK.setText("Quản Lý Phiếu Khám");
        mniPK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniPKMouseClicked(evt);
            }
        });
        mniPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPKActionPerformed(evt);
            }
        });
        mniBS.add(mniPK);

        mniDoanhThu.setText("Doanh Thu");
        mniDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDoanhThuMouseClicked(evt);
            }
        });
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mniBS.add(mniDoanhThu);

        jMenuBar1.add(mniBS);

        mniHuongDan.setText("Hướng Dẫn Sử Dụng");

        jMenuItem9.setText("Hướng dẫn");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mniHuongDan.add(jMenuItem9);

        jMenuBar1.add(mniHuongDan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBNActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyBenhNhan(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_mniBNActionPerformed

    private void lblBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyBenhNhan(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblBenhNhanMouseClicked

    private void lblThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblThuocMouseClicked

    private void lblPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyPhieuKham(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblPhieuKhamMouseClicked

    private void lblDonThocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThocMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyDonThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblDonThocMouseClicked

    private void lblDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            }
            new ThongKe(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_lblDoanhThuMouseClicked

    private void lblTextBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextBacSiMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            // Nếu đã đăng nhập, tạo mới một BacSiPage và hiển thị nó
            BacSiPage bacSiPage = new BacSiPage(); // hoặc truyền tham số nếu cần
            bacSiPage.setVisible(true);

            // Nếu cần, có thể đóng frame hiện tại
            this.dispose(); // Đóng frame hiện tại nếu không muốn để lại nó trên màn hình
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblTextBacSiMouseClicked

    private void lblBenhNhanTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanTextMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyBenhNhan(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblBenhNhanTextMouseClicked

    private void lblThuocTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocTextMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblThuocTextMouseClicked

    private void lblPhieuKhamTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamTextMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyPhieuKham(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblPhieuKhamTextMouseClicked

    private void lblDonThuocTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThuocTextMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyDonThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblDonThuocTextMouseClicked

    private void lblDoanhThuTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            }
            new ThongKe(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }//GEN-LAST:event_lblDoanhThuTextMouseClicked

    private void lblTextBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextBacSiMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblTextBacSi, WIDTH, ABORT, ERROR);
        cl.setColor(lblTextBacSi);
    }//GEN-LAST:event_lblTextBacSiMouseEntered

    private void lblTextBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextBacSiMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblTextBacSi);
        cl.resetColor(lblTextBacSi);
    }//GEN-LAST:event_lblTextBacSiMouseExited

    private void lblBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBacSiMouseClicked
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            // Nếu đã đăng nhập, tạo mới một BacSiPage và hiển thị nó
            BacSiPage bacSiPage = new BacSiPage(); // hoặc truyền tham số nếu cần
            bacSiPage.setVisible(true);

            // Nếu cần, có thể đóng frame hiện tại
            this.dispose(); // Đóng frame hiện tại nếu không muốn để lại nó trên màn hình
        }
    }//GEN-LAST:event_lblBacSiMouseClicked

    private void lblBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBacSiMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblTextBacSi, WIDTH, ABORT, ERROR);
        cl.setColor(lblTextBacSi);
//       ImageIcon imgThisImg = new ImageIcon("Background/Victim1.jpg");
//       lblBacSi.setIcon(imgThisImg);
//        
//        JLabel jLabelObject = new JLabel();
//        jLabelObject.setIcon(new ImageIcon("Background/bloom.gif"));
    }//GEN-LAST:event_lblBacSiMouseEntered

    private void lblBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBacSiMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblTextBacSi);
        cl.resetColor(lblTextBacSi);
    }//GEN-LAST:event_lblBacSiMouseExited

    private void lblBenhNhanTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanTextMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblBenhNhanText, WIDTH, ABORT, ERROR);
        cl.setColor(lblBenhNhanText);
    }//GEN-LAST:event_lblBenhNhanTextMouseEntered

    private void lblBenhNhanTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanTextMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblBenhNhanText);
        cl.resetColor(lblBenhNhanText);
    }//GEN-LAST:event_lblBenhNhanTextMouseExited

    private void lblBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblBenhNhanText, WIDTH, ABORT, ERROR);
        cl.setColor(lblBenhNhanText);
    }//GEN-LAST:event_lblBenhNhanMouseEntered

    private void lblBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBenhNhanMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblBenhNhanText);
        cl.resetColor(lblBenhNhanText);
    }//GEN-LAST:event_lblBenhNhanMouseExited

    private void lblThuocTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocTextMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblThuocText, WIDTH, ABORT, ERROR);
        cl.setColor(lblThuocText);
    }//GEN-LAST:event_lblThuocTextMouseEntered

    private void lblThuocTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocTextMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblThuocText);
        cl.resetColor(lblThuocText);
    }//GEN-LAST:event_lblThuocTextMouseExited

    private void lblThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblThuocText, WIDTH, ABORT, ERROR);
        cl.setColor(lblThuocText);
    }//GEN-LAST:event_lblThuocMouseEntered

    private void lblThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblThuocText);
        cl.resetColor(lblThuocText);
    }//GEN-LAST:event_lblThuocMouseExited

    private void lblPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblPhieuKhamText, WIDTH, ABORT, ERROR);
        cl.setColor(lblPhieuKhamText);
    }//GEN-LAST:event_lblPhieuKhamMouseEntered

    private void lblPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblPhieuKhamText);
        cl.resetColor(lblPhieuKhamText);
    }//GEN-LAST:event_lblPhieuKhamMouseExited

    private void lblPhieuKhamTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamTextMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblPhieuKhamText, WIDTH, ABORT, ERROR);
        cl.setColor(lblPhieuKhamText);
    }//GEN-LAST:event_lblPhieuKhamTextMouseEntered

    private void lblPhieuKhamTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamTextMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblPhieuKhamText);
        cl.resetColor(lblPhieuKhamText);
    }//GEN-LAST:event_lblPhieuKhamTextMouseExited

    private void lblDonThocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThocMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblDonThuocText, WIDTH, ABORT, ERROR);
        cl.setColor(lblDonThuocText);
    }//GEN-LAST:event_lblDonThocMouseEntered

    private void lblDonThocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThocMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblDonThuocText);
        cl.resetColor(lblDonThuocText);
    }//GEN-LAST:event_lblDonThocMouseExited

    private void lblDonThuocTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThuocTextMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblDonThuocText, WIDTH, ABORT, ERROR);
        cl.setColor(lblDonThuocText);
    }//GEN-LAST:event_lblDonThuocTextMouseEntered

    private void lblDonThuocTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonThuocTextMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblDonThuocText);
        cl.resetColor(lblDonThuocText);
    }//GEN-LAST:event_lblDonThuocTextMouseExited

    private void lblDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblDoanhThuText, WIDTH, ABORT, ERROR);
        cl.setColor(lblDoanhThuText);
    }//GEN-LAST:event_lblDoanhThuMouseEntered

    private void lblDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblDoanhThuText);
        cl.resetColor(lblDoanhThuText);
    }//GEN-LAST:event_lblDoanhThuMouseExited

    private void lblDoanhThuTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseEntered
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblDoanhThuText, WIDTH, ABORT, ERROR);
        cl.setColor(lblDoanhThuText);
    }//GEN-LAST:event_lblDoanhThuTextMouseEntered

    private void lblDoanhThuTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseExited
        // TODO add your handling code here:
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblDoanhThuText);
        cl.resetColor(lblDoanhThuText);
    }//GEN-LAST:event_lblDoanhThuTextMouseExited

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
        Auth.clear();
        new Login(this, true).setVisible(true);
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            }
            new ThongKe(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyBacSi(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mniThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniThuocMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mniThuocMouseClicked

    private void mniDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDTMouseClicked

    private void mniPKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniPKMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mniPKMouseClicked

    private void mniDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDoanhThuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mniDoanhThuMouseClicked

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new HuongDanSuDung(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mniThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThuocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_mniThuocActionPerformed

    private void mniDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDTActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyDonThuoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_mniDTActionPerformed

    private void mniPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPKActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyPhieuKham(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_mniPKActionPerformed

    private void mniEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniEXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBacSi;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblBenhNhan;
    private javax.swing.JLabel lblBenhNhanText;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblClock1;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblDoanhThuText;
    private javax.swing.JLabel lblDonThoc;
    private javax.swing.JLabel lblDonThuocText;
    private javax.swing.JLabel lblPhieuKham;
    private javax.swing.JLabel lblPhieuKhamText;
    private javax.swing.JLabel lblTextBacSi;
    private javax.swing.JLabel lblThuoc;
    private javax.swing.JLabel lblThuocText;
    private javax.swing.JMenuItem mniBN;
    private javax.swing.JMenu mniBS;
    private javax.swing.JMenuItem mniDT;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniEXIT;
    private javax.swing.JMenu mniHuongDan;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniPK;
    private javax.swing.JMenuItem mniThuoc;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setLocationRelativeTo(null);
        new Login(this, true).setVisible(true);
        //effect.setIcon(new ImageIcon(getClass().getResource("/Background/hover2.gif")));
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formattime = new SimpleDateFormat("hh:mm:ss a");
                String text = formattime.format(now);
                lblClock.setText(text);
            }
        }).start();
    }
}
