/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongkham;

import Entity.BacSi;
import DAO.BacSiDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Auth;
import util.MsgBox;
import util.Xjdbc;

/**
 *
 * @author ADMIN
 */
public class QuanLyBacSi extends javax.swing.JDialog {

    /**
     * Creates new form Doctor
     */
    public QuanLyBacSi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtMaBS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenBS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtChuyenNganh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(738, 932));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Thông Tin Bác Sĩ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(3, 3, 151, 22);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(3, 32, 890, 3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ Và Tên BS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(15, 83, 111, 22);

        txtMaBS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtMaBS);
        txtMaBS.setBounds(140, 40, 414, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã Bác Sĩ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(15, 41, 77, 22);

        txtTenBS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtTenBS);
        txtTenBS.setBounds(140, 80, 414, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Giới Tính");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(15, 125, 71, 22);

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel2.add(rdoNam);
        rdoNam.setBounds(138, 125, 49, 21);

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel2.add(rdoNu);
        rdoNu.setBounds(211, 125, 39, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SĐT");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(620, 130, 57, 30);

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtSDT);
        txtSDT.setBounds(680, 130, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Ghi chú");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 70, 22);

        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtGhiChu);
        txtGhiChu.setBounds(140, 220, 410, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tuổi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(619, 41, 35, 22);

        txtTuoi.setEditable(false);
        txtTuoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtTuoi);
        txtTuoi.setBounds(685, 43, 50, 30);

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        jPanel2.add(txtNgaySinh);
        txtNgaySinh.setBounds(747, 43, 121, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Chuyên Ngành");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(619, 83, 116, 22);

        txtChuyenNganh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtChuyenNganh);
        txtChuyenNganh.setBounds(750, 80, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Địa Chỉ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 170, 57, 22);

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(txtDiaChi);
        txtDiaChi.setBounds(140, 170, 410, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 908, 280));

        tblBang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Bác Sĩ", "Họ Và Tên", "Chuyên Ngành", "Ngày sinh", "Ghi chú", "Địa Chỉ", "SĐT", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang.setRowHeight(30);
        tblBang.setRowMargin(4);
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 910, 340));

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 110, 50));

        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 110, 50));

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, 110, 50));

        btnAdd.setText("Thêm Mới");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 110, 50));

        btnNew.setText("Nhập Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 100, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/vector-MAY-2020-112.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 932, 738));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền thực hiện các tác vụ này!");
            return;
        }
        if (checkform()) {
            if (checkInsert()) {
                this.insert();
            }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền thực hiện các tác vụ này!");
            return;
        }
       
        if (checkform()) {
//            MsgBox.confirm(this, "Vui lòng không thay đổi mã bác sĩ khi cập nhật");
            this.update();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblBang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền thực hiện các tác vụ này!");
            return;
        }
        this.delete();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        this.clearForm();
        // Check if txtMaBS is disabled, and enable it if necessary
        if (!txtMaBS.isEnabled()) {
            txtMaBS.setEnabled(true);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyBacSi dialog = new QuanLyBacSi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtChuyenNganh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaBS;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenBS;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
 BacSiDAO dao = new BacSiDAO();
    int row = -1;

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblBang.getModel();
        model.setRowCount(0);
        try {
            List<BacSi> list = dao.selectALL();
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd"); // Assuming this is the format in your database
            SimpleDateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy"); // Desired output format

            for (BacSi bs : list) {
                // Parse the date string from the database
                String dateString = bs.getNgaysinh(); // e.g., "YYYY-MM-DD"
                String formattedDate = dateString; // Default to the original value

                try {
                    Date date = inputFormat.parse(dateString); // Parse the original date string
                    formattedDate = outputFormat.format(date); // Format it to DD/MM/YYYY
                } catch (ParseException e) {
                    System.out.println("Date parsing error: " + e.getMessage());
                    // Optionally, handle the error or set formattedDate to an error message
                }

                Object[] row = {
                    bs.getMaBS(),
                    bs.getTenBS(),
                    bs.getChuyennganh(),
                    formattedDate, // Use the formatted date here
                    bs.getGhiChu(),
                    bs.getDiachi(),
                    bs.getSDT(),
                    bs.getGioitinh(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    BacSi getForm() {
        BacSi nv = new BacSi();
        nv.setMaBS(txtMaBS.getText());
        nv.setTenBS(txtTenBS.getText());
        nv.setChuyennganh(txtChuyenNganh.getText());
        if (rdoNam.isSelected()) {
            nv.setGioitinh(rdoNam.getText());
        }
        if (rdoNu.isSelected()) {
            nv.setGioitinh(rdoNu.getText());
        }
        nv.setDiachi(txtDiaChi.getText());
        nv.setGhiChu(txtGhiChu.getText());
        nv.setNgaysinh(txtNgaySinh.getText());
        nv.setSDT(txtSDT.getText());

        return nv;
    }

    void setForm(BacSi nv) {
        txtMaBS.setText(nv.getMaBS());
        txtTenBS.setText(nv.getTenBS());
        txtChuyenNganh.setText(nv.getChuyennganh());
        txtGhiChu.setText(nv.getGhiChu());
        txtNgaySinh.setText(nv.getNgaysinh());
        txtSDT.setText(nv.getSDT());
        txtDiaChi.setText(nv.getDiachi());

        // Set gender
        if (nv.getGioitinh().equalsIgnoreCase("Nam")) {
            rdoNam.setSelected(true);
        } else if (nv.getGioitinh().equalsIgnoreCase("Nữ")) {
            rdoNu.setSelected(true);
        }

        txtSDT.setText(nv.getSDT());

        // Format the date from ngaysinh (String) to DD/MM/YYYY
        String ngaysinhStr = nv.getNgaysinh(); // Assuming this returns a date in "yyyy-MM-dd" format
        if (ngaysinhStr != null) {
            try {
                SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date date = inputFormat.parse(ngaysinhStr);
                String formattedDate = outputFormat.format(date);
                txtNgaySinh.setText(formattedDate);
            } catch (ParseException e) {
                e.printStackTrace();
                txtNgaySinh.setText(""); // Handle parsing error
            }
        } else {
            txtNgaySinh.setText(""); // Handle null case
        }

        txtTuoi.setText(String.valueOf(TinhTuoi()));
    }

    void edit() {
        String mabs = (String) tblBang.getValueAt(this.row, 0);
        BacSi nv = dao.selectById(mabs);
        this.setForm(nv);
        txtMaBS.setEnabled(false); // Disable the txtMaBS field
    }

    void insert() {
        BacSi bs = this.getForm();
        try {
            // Convert the date format from dd/MM/yyyy to yyyy-MM-dd
            String inputDate = bs.getNgaysinh(); // Assuming ngaySinh is a String in dd/MM/yyyy format

            // Define the date format you expect to receive (dd/MM/yyyy)
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = inputFormat.parse(inputDate);  // Parse the input date

            // Define the date format the database expects (yyyy-MM-dd)
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = outputFormat.format(date);  // Format the date

            // Set the formatted date back into the object
            bs.setNgaysinh(formattedDate);
            dao.insert(bs);
            this.fillTable(); // đỗ lại bảng
            this.clearForm(); // xóa trắng form
            MsgBox.alert(this, "Thêm mới thành công!");

        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            System.out.println(e);
        }
    }

    void update() {
        BacSi bs = this.getForm();
        try {
            String inputDate = bs.getNgaysinh(); // Assuming ngaySinh is a String in dd/MM/yyyy format

            // Define the date format you expect to receive (dd/MM/yyyy)
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = inputFormat.parse(inputDate);  // Parse the input date

            // Define the date format the database expects (yyyy-MM-dd)
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = outputFormat.format(date);  // Format the date

            // Set the formatted date back into the object
            bs.setNgaysinh(formattedDate);
            dao.update(bs); // cập nhật
            this.fillTable(); // đổ lại bảng

            this.setForm(bs);

            MsgBox.alert(this, "Cập nhật thành công!");

        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void init() {
        setLocationRelativeTo(null); // đưa cửa sổ ra giữa màn hình
        this.fillTable(); // đổ dữ liệu nhân viên vào bảng
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa bác sĩ!");
        } else {
            String manv = txtMaBS.getText();
            if (manv.equals(Auth.user.getVaiTro())) {
                MsgBox.alert(this, "Bạn không được xóa chính bạn!");
            } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa bác sĩ này?")) {
                try {
                    dao.delete(manv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công!");

                } catch (Exception e) {
                    System.out.println(e);
                    MsgBox.alert(this, "Xóa thất bại!");
                    MsgBox.alert(this, "Hãy xóa các đơn thuốc và phiếu khám do bác sĩ này phụ trách!");
                }
            }
        }
    }

    void clearForm() {
        txtChuyenNganh.setText("");
        txtGhiChu.setText("");
        txtMaBS.setText("");
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtTenBS.setText("");
        txtTuoi.setText("");
        txtDiaChi.setText("");
        rdoNam.setSelected(true);
    }

    boolean checkform() {
        String sdt = "0[0-9]{9}";
        String regex = "^\\d{2}/\\d{2}/\\d{4}$";
        if (txtMaBS.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Mã bác sĩ không được trống!");
            return false;
        } else if (txtChuyenNganh.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập chuyên ngành!");
            return false;
        } else if (txtGhiChu.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập địa chỉ!");
            return false;
        } else if (txtNgaySinh.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập Ngày sinh!");
            return false;
        } else if (txtSDT.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập số điện thoại!");
            return false;
        } else if (txtTenBS.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập tên bác sĩ!");
            return false;
        } else if (!txtNgaySinh.getText().matches(regex)) {
            MsgBox.alert(this, "Bạn nhập sai định dạng ngày sinh, hãy kiểm tra lại(DD/MM/YYYY)!");
            return false;
        } else if (!txtSDT.getText().matches(sdt)) {
            MsgBox.alert(this, "Không đúng định dạng số điện thoại");
            return false;
        }
        return true;
    }

    int TinhTuoi() {
        try {
            BacSiDAO dao = new BacSiDAO();
            BacSi list = dao.selectById(txtMaBS.getText());
            String ngaysinhh = list.getNgaysinh(); // Assuming the format is "YYYY-MM-DD"

            // Parse the birth date
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Calendar birthCal = Calendar.getInstance();
            birthCal.setTime(sdf.parse(ngaysinhh));

            // Get current date
            Calendar today = Calendar.getInstance();

            // Calculate age
            int tuoi = today.get(Calendar.YEAR) - birthCal.get(Calendar.YEAR);

            // Adjust for whether the birthday has occurred this year
            if (today.get(Calendar.MONTH) < birthCal.get(Calendar.MONTH)
                    || (today.get(Calendar.MONTH) == birthCal.get(Calendar.MONTH) && today.get(Calendar.DAY_OF_MONTH) < birthCal.get(Calendar.DAY_OF_MONTH))) {
                tuoi--;
            }

            return tuoi;

        } catch (ParseException e) {
            e.printStackTrace(); // Handle the exception as needed
            return 0; // Or handle as needed
        }
    }

    public List<String> selectID() {
        String sql = "select MaBS from BacSi";
        List<String> list = new ArrayList<>();
        try {
            ResultSet rs = Xjdbc.query(sql);
            while (rs.next()) {
                list.add(rs.getString("MaBS"));
            }
            rs.getStatement().getConnection().close();
            return list;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    boolean checkInsert() {
        List<String> list = selectID();
        for (String ma : list) {
            if (txtMaBS.getText().equalsIgnoreCase(ma)) {
                MsgBox.alert(this, "Mã bác sĩ đã tồn tại!");
                return false;
            }
        }
        return true;
    }
}
